const styles = {
    page: {
        padding: "4px 8px 18px",
        background: "transparent",
        minHeight: "100%",
        maxWidth: 1288,
        margin: "0 auto",
    },
    eyebrow: {
        color: "#7480a2",
        textTransform: "uppercase",
        letterSpacing: "0.14em",
        fontSize: 13,
        fontWeight: 800,
        marginBottom: 8,
    },
    pageHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: 20,
        marginBottom: 18,
        padding: "4px 10px 10px",
    },
    headerActions: {
        display: "flex",
        gap: 10,
        alignItems: "center",
        flexWrap: "wrap",
    },
    linkButton: {
        textDecoration: "none",
        padding: "12px 16px",
        borderRadius: 14,
        background: "rgba(255,255,255,0.92)",
        color: "var(--text-main)",
        fontWeight: 700,
        border: "1px solid var(--panel-border)",
        boxShadow: "0 10px 20px rgba(118, 136, 186, 0.08)",
    },
    section: {
        background: "linear-gradient(180deg, rgba(255,255,255,0.96) 0%, rgba(251,252,255,0.92) 100%)",
        borderRadius: 30,
        padding: "22px 20px 18px",
        border: "1px solid rgba(224, 231, 244, 0.96)",
        boxShadow: "0 18px 48px rgba(113, 130, 176, 0.08)",
        marginBottom: 20,
    },
    sectionTitleRow: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        marginBottom: 14,
        flexWrap: "wrap",
    },
    sectionTitle: {
        margin: 0,
        fontSize: 17,
        letterSpacing: "-0.02em",
        fontWeight: 800,
    },
    headerGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: 14,
    },
    compactHeaderCard: {
        display: "grid",
        gap: 16,
        padding: "4px 0 0",
        borderRadius: 22,
        border: "none",
        background: "transparent",
    },
    compactHeaderRow: {
        display: "grid",
        gap: 14,
        alignItems: "end",
    },
    compactField: {
        display: "grid",
        gap: 8,
        minWidth: 0,
        alignContent: "start",
    },
    compactLabel: {
        color: "#667091",
        fontSize: 11,
        fontWeight: 700,
        whiteSpace: "nowrap",
        letterSpacing: "0.01em",
    },
    compactControlWrap: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) auto",
        alignItems: "center",
        gap: 8,
        minWidth: 0,
    },
    compactInput: {
        width: "100%",
        minWidth: 0,
        padding: "11px 14px",
        borderRadius: 12,
        border: "1px solid #dbe2f0",
        background: "#ffffff",
        color: "var(--field-text)",
        outline: "none",
        boxShadow: "inset 0 1px 0 rgba(255,255,255,0.8)",
        minHeight: 44,
    },
    compactReadonlyInput: {
        width: "100%",
        minWidth: 0,
        padding: "11px 14px",
        borderRadius: 12,
        border: "1px solid #dbe2f0",
        background: "#ffffff",
        color: "var(--text-main)",
        outline: "none",
        minHeight: 44,
    },
    compactPlusButton: {
        border: "none",
        borderRadius: 999,
        width: 34,
        height: 34,
        padding: 0,
        background: "var(--button-primary)",
        color: "var(--button-primary-text)",
        cursor: "pointer",
        fontWeight: 700,
        flexShrink: 0,
    },
    label: {
        display: "block",
        fontSize: 12,
        fontWeight: 700,
        marginBottom: 6,
        color: "var(--text-main)",
        textTransform: "uppercase",
        letterSpacing: "0.04em",
    },
    inputWrap: {
        display: "flex",
        alignItems: "center",
        gap: 8,
    },
    input: {
        width: "100%",
        padding: "11px 12px",
        borderRadius: 12,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
        outline: "none",
    },
    textarea: {
        width: "100%",
        minHeight: 96,
        padding: "11px 12px",
        borderRadius: 12,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
        outline: "none",
        resize: "vertical",
    },
    readonlyInput: {
        background: "var(--surface-soft)",
        color: "var(--text-soft)",
    },
    subtleText: {
        margin: "6px 0 0",
        color: "#78829c",
        fontSize: 13,
        lineHeight: 1.55,
    },
    keyboardHint: {
        color: "#8a93ab",
        fontSize: 12,
    },
    statusPill: {
        padding: "12px 18px",
        borderRadius: 999,
        background: "linear-gradient(180deg, #eef9f1 0%, #e5f7ec 100%)",
        color: "var(--success-soft-text)",
        fontSize: 12,
        fontWeight: 700,
        border: "1px solid #d9efe1",
    },
    addRowButton: {
        borderRadius: 14,
        padding: "12px 18px",
        background: "linear-gradient(180deg, #eef9f1 0%, #e5f7ec 100%)",
        color: "var(--success-soft-text)",
        fontWeight: 700,
        cursor: "pointer",
        border: "1px solid #d9efe1",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
        tableLayout: "fixed",
        minWidth: 1320,
    },
    tableHeadCell: {
        padding: "10px 12px",
        textAlign: "left",
        fontSize: 12,
        fontWeight: 700,
        color: "var(--text-main)",
        background: "transparent",
        borderBottom: "1px solid var(--line)",
        whiteSpace: "nowrap",
        textTransform: "uppercase",
    },
    tableBodyCell: {
        padding: "10px 12px",
        borderBottom: "1px solid var(--line)",
        verticalAlign: "middle",
    },
    serialCell: {
        minWidth: 42,
        color: "var(--text-soft)",
        fontWeight: 700,
        textAlign: "center",
    },
    fieldXs: { flex: "0 0 120px", minWidth: 120 },
    fieldSm: { minWidth: 0 },
    fieldMd: { minWidth: 0 },
    fieldLg: { minWidth: 0 },
    fieldWide: { minWidth: 0 },
    fieldDate: { minWidth: 0 },
    inlineField: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        minWidth: 0,
    },
    cellInput: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid #d9dee3",
        background: "#ffffff",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    errorCellInput: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid var(--danger-soft-border)",
        background: "var(--danger-soft-bg)",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    cellInputWide: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid #d9dee3",
        background: "#ffffff",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    errorCellInputWide: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid var(--danger-soft-border)",
        background: "var(--danger-soft-bg)",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    cellInputSmall: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid #d9dee3",
        background: "#ffffff",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    cellInputTiny: {
        width: "100%",
        padding: "10px 12px",
        borderRadius: 10,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    errorCellInputSmall: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid var(--danger-soft-border)",
        background: "var(--danger-soft-bg)",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    readonlyCell: {
        width: "100%",
        minHeight: 40,
        padding: "0.45rem 0.75rem",
        borderRadius: 6,
        border: "1px solid #d9dee3",
        background: "#ffffff",
        color: "var(--text-soft)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    plusButton: {
        border: "none",
        borderRadius: 6,
        width: 32,
        height: 40,
        background: "transparent",
        color: "var(--text-main)",
        cursor: "pointer",
        fontWeight: 700,
        flexShrink: 0,
    },
    removeButton: {
        border: "none",
        borderRadius: 10,
        padding: "9px 12px",
        background: "var(--danger-soft-bg)",
        color: "var(--status-error)",
        cursor: "pointer",
        fontWeight: 700,
    },
    rowDeleteButton: {
        border: "1px solid #d9dee3",
        borderRadius: 6,
        width: 32,
        height: 40,
        background: "#ffffff",
        color: "var(--text-muted)",
        cursor: "pointer",
        fontWeight: 800,
    },
    mobileItemsWrap: {
        display: "none",
        gap: 14,
        marginTop: 14,
    },
    mobileItemCard: {
        display: "grid",
        gap: 14,
        padding: 16,
        borderRadius: 18,
    },
    mobileItemCardHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: 12,
    },
    mobileItemIndex: {
        fontWeight: 800,
        color: "var(--text-main)",
        marginBottom: 4,
    },
    mobileItemGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: 12,
    },
    detailField: {
        display: "grid",
        gap: 6,
        minWidth: 0,
    },
    detailLabel: {
        fontSize: 11,
        fontWeight: 800,
        letterSpacing: "0.05em",
        textTransform: "uppercase",
        color: "var(--text-soft)",
    },
    detailInput: {
        width: "100%",
        padding: "9px 10px",
        borderRadius: 10,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    errorDetailInput: {
        width: "100%",
        padding: "9px 10px",
        borderRadius: 10,
        border: "1px solid var(--danger-soft-border)",
        background: "var(--danger-soft-bg)",
        color: "var(--text-main)",
        boxSizing: "border-box",
        minWidth: 0,
    },
    purchaseFooterPanel: {
        display: "grid",
        gap: 18,
        marginTop: 0,
        padding: "18px 18px 16px",
        borderRadius: 30,
        background: "linear-gradient(180deg, rgba(255,255,255,0.96) 0%, rgba(251,252,255,0.92) 100%)",
        border: "1px solid rgba(224, 231, 244, 0.96)",
        boxShadow: "0 18px 44px rgba(113, 130, 176, 0.08)",
    },
    historyPanel: {
        display: "grid",
        gap: 10,
    },
    historyHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: 12,
        flexWrap: "wrap",
    },
    historyTitle: {
        color: "var(--text-main)",
        fontWeight: 800,
        fontSize: 17,
    },
    historyTableWrap: {
        overflowX: "auto",
        border: "1px solid #e7ecf6",
        borderRadius: 16,
        background: "#ffffff",
    },
    historyTable: {
        width: "100%",
        minWidth: 1120,
        borderCollapse: "collapse",
    },
    historyHeadCell: {
        padding: "9px 10px",
        background: "var(--surface-soft)",
        borderBottom: "1px solid var(--line)",
        fontSize: 12,
        fontWeight: 700,
        color: "var(--text-main)",
        textAlign: "left",
        whiteSpace: "nowrap",
    },
    historyCell: {
        padding: "10px 10px",
        borderBottom: "1px solid var(--line)",
        color: "var(--text-main)",
        fontSize: 13,
        whiteSpace: "nowrap",
    },
    historyEmptyCell: {
        padding: "16px 12px",
        textAlign: "center",
        color: "var(--text-soft)",
        fontSize: 13,
    },
    mobileHistoryCards: {
        display: "none",
        gap: 12,
    },
    mobileHistoryCard: {
        padding: 14,
        borderRadius: 16,
    },
    mobileHistoryGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: 10,
    },
    purchaseFooterLower: {
        display: "grid",
        gridTemplateColumns: "1.45fr 0.75fr",
        gap: 20,
        alignItems: "start",
    },
    purchaseFooterLeft: {
        display: "grid",
        gap: 14,
    },
    footerNarrationField: {
        display: "grid",
        gridTemplateColumns: "60px minmax(0, 1fr)",
        gap: 12,
        alignItems: "start",
    },
    footerNarrationInput: {
        width: "100%",
        minHeight: 86,
        padding: "12px 14px",
        borderRadius: 12,
        border: "1px solid #dbe2f0",
        background: "#ffffff",
        color: "var(--text-main)",
        resize: "vertical",
    },
    footerQuickRow: {
        display: "flex",
        gap: 12,
        alignItems: "flex-start",
        flexWrap: "wrap",
    },
    mrpPreviewPanel: {
        display: "grid",
        gap: 10,
        padding: 14,
        borderRadius: 14,
        border: "1px solid var(--line)",
        background: "var(--surface-soft)",
    },
    mrpPreviewTitle: {
        color: "var(--text-main)",
        fontWeight: 800,
        fontSize: 14,
    },
    mrpPreviewList: {
        display: "grid",
        gap: 8,
    },
    mrpPreviewItem: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        padding: "10px 12px",
        borderRadius: 12,
        background: "var(--surface)",
        border: "1px solid var(--line)",
        color: "var(--text-main)",
        fontSize: 13,
    },
    taxMiniTable: {
        display: "grid",
        gridTemplateColumns: "0.7fr 1fr 1fr",
        border: "1px solid #dbe2f0",
        borderRadius: 12,
        overflow: "hidden",
        minWidth: 360,
    },
    taxMiniHead: {
        padding: "10px 12px",
        background: "#f7f9fe",
        borderRight: "1px solid #e4e9f4",
        fontSize: 12,
        fontWeight: 700,
        textAlign: "center",
    },
    taxMiniCell: {
        padding: "12px 10px",
        borderTop: "1px solid #e4e9f4",
        borderRight: "1px solid #e4e9f4",
        textAlign: "center",
        background: "#ffffff",
        color: "var(--text-main)",
    },
    taxMiniInput: {
        width: "100%",
        minWidth: 0,
        border: "none",
        outline: "none",
        boxSizing: "border-box",
    },
    footerButtonRow: {
        display: "flex",
        gap: 10,
        flexWrap: "wrap",
        alignItems: "center",
    },
    purchaseFooterSummary: {
        display: "grid",
        gap: 10,
        padding: 18,
        borderRadius: 20,
        border: "1px solid #e7ecf6",
        background: "linear-gradient(180deg, #fbfcff 0%, #f8faff 100%)",
    },
    summaryLine: {
        display: "grid",
        gridTemplateColumns: "1fr minmax(110px, auto)",
        gap: 10,
        alignItems: "center",
        color: "var(--text-main)",
        fontSize: 14,
    },
    summaryInlineField: {
        display: "inline-flex",
        alignItems: "center",
        gap: 8,
    },
    summaryMiniInput: {
        width: 96,
        padding: "10px 12px",
        borderRadius: 12,
        border: "1px solid #dbe2f0",
        background: "#ffffff",
        color: "var(--text-main)",
        textAlign: "right",
    },
    summaryTotalLine: {
        display: "grid",
        gridTemplateColumns: "1fr auto",
        gap: 10,
        alignItems: "center",
        paddingTop: 10,
        marginTop: 6,
        borderTop: "1px solid var(--line)",
        color: "var(--text-main)",
        fontWeight: 800,
    },
    attachmentList: {
        display: "grid",
        gap: 10,
    },
    attachmentRow: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        padding: "14px 16px",
        borderRadius: 14,
        background: "var(--surface-soft)",
        border: "1px solid var(--line)",
    },
    billScannerGrid: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
        gap: 14,
        marginBottom: 14,
    },
    billScannerPanel: {
        display: "grid",
        gap: 12,
        alignContent: "start",
        minWidth: 0,
        padding: 16,
        borderRadius: 16,
        background: "#ffffff",
        border: "1px solid var(--line)",
        boxShadow: "0 8px 24px rgba(113, 130, 176, 0.08)",
    },
    billScannerIcon: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        width: 42,
        height: 42,
        borderRadius: 12,
        background: "var(--primary-light)",
        color: "var(--primary)",
        fontSize: 22,
    },
    scanSummaryHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: 12,
    },
    scanConfidencePill: {
        display: "inline-flex",
        alignItems: "center",
        minHeight: 32,
        padding: "6px 10px",
        borderRadius: 999,
        background: "rgba(105,108,255,.12)",
        color: "var(--primary)",
        fontWeight: 800,
        fontSize: 12,
        whiteSpace: "nowrap",
    },
    scanFieldGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: 10,
    },
    scanWarningBox: {
        display: "grid",
        gap: 6,
        padding: 12,
        borderRadius: 12,
        background: "rgba(255,171,0,.12)",
        color: "#7a5700",
        fontSize: 13,
        fontWeight: 600,
    },
    checkboxRow: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        marginTop: 8,
        color: "var(--text-main)",
        fontSize: 13,
    },
    secondaryButton: {
        border: "1px solid var(--line)",
        borderRadius: 12,
        padding: "12px 16px",
        background: "var(--surface)",
        color: "var(--text-main)",
        fontWeight: 700,
        cursor: "pointer",
    },
    primaryButton: {
        border: "none",
        borderRadius: 12,
        padding: "12px 18px",
        background: "var(--button-primary)",
        color: "var(--button-primary-text)",
        fontWeight: 700,
        cursor: "pointer",
    },
    modalBackdrop: {
        position: "fixed",
        inset: 0,
        background: "rgba(0, 0, 0, 0.45)",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        zIndex: 1000,
    },
    modal: {
        width: "min(960px, 100%)",
        maxHeight: "90vh",
        overflow: "auto",
        background: "var(--surface)",
        borderRadius: 22,
        padding: 20,
        boxShadow: "var(--shadow)",
    },
    modalHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: 12,
        marginBottom: 16,
    },
    modalGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: 14,
    },
    closeButton: {
        border: "none",
        borderRadius: 10,
        padding: "10px 12px",
        background: "var(--surface-soft)",
        color: "var(--text-main)",
        cursor: "pointer",
    },
    fetchButton: {
        border: "none",
        borderRadius: 10,
        padding: "10px 12px",
        background: "var(--accent)",
        color: "var(--button-primary-text)",
        fontWeight: 700,
        cursor: "pointer",
        whiteSpace: "nowrap",
    },
    inlineLink: {
        whiteSpace: "nowrap",
        textDecoration: "none",
        color: "var(--accent)",
        fontWeight: 700,
        fontSize: 13,
    },
    statusBanner: {
        padding: "12px 14px",
        borderRadius: 16,
        background: "rgba(23, 38, 31, 0.08)",
        border: "1px solid var(--line)",
        color: "var(--text-main)",
        fontWeight: 700,
    },
};


export default styles;
