const styles = {
    page: { display: "grid", gap: 20 },
    desktopHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 18,
        flexWrap: "wrap",
        padding: 24,
        borderRadius: 28,
        background: "var(--hero-gradient-soft)",
        border: "1px solid var(--panel-border-soft)",
    },
    pageEyebrow: {
        color: "var(--text-soft)",
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        fontSize: 12,
        fontWeight: 800,
    },
    desktopTitle: { margin: "8px 0 10px", fontSize: "1.85rem", lineHeight: 1.05, maxWidth: 720 },
    desktopText: { margin: 0, color: "var(--text-soft)", maxWidth: 740 },
    desktopActions: { display: "flex", gap: 10, flexWrap: "wrap" },
    mobileShortcutBar: { display: "none" },
    primaryButton: {
        border: "none",
        borderRadius: 16,
        padding: "12px 16px",
        background: "var(--button-primary)",
        color: "var(--button-primary-text)",
        fontWeight: 800,
        cursor: "pointer",
    },
    secondaryButton: {
        border: "1px solid var(--line)",
        borderRadius: 16,
        padding: "12px 16px",
        background: "var(--button-secondary-bg)",
        color: "var(--text-main)",
        fontWeight: 700,
        cursor: "pointer",
    },
    dangerButton: {
        border: "none",
        borderRadius: 16,
        padding: "12px 16px",
        background: "var(--status-error-bg, #c84d4d)",
        color: "var(--status-error-text, #fff7f7)",
        fontWeight: 800,
        cursor: "pointer",
    },
    statusMessage: {
        padding: "12px 16px",
        borderRadius: 16,
        background: "var(--success-soft-bg)",
        color: "var(--success-soft-text)",
        border: "1px solid var(--success-soft-border)",
        fontWeight: 700,
    },
    posShell: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) 220px",
        gap: 18,
        alignItems: "start",
    },
    billingDesk: { display: "grid", gap: 18 },
    captureHeaderCard: { padding: 18, display: "grid", gap: 16 },
    captureHeaderGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
        gap: 12,
    },
    captureSearchRow: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) auto auto auto",
        gap: 10,
        alignItems: "end",
    },
    captureSearchInputWrap: { display: "grid", gap: 8 },
    captureSearchLabel: {
        width: "fit-content",
        padding: "4px 9px",
        borderRadius: 999,
        background: "var(--surface-soft)",
        color: "var(--text-soft)",
        fontSize: 11,
        fontWeight: 800,
        letterSpacing: "0.04em",
    },
    captureSearchInput: {
        width: "100%",
        padding: "13px 14px",
        borderRadius: 14,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
        fontSize: 15,
        fontWeight: 700,
    },
    captureInfoRow: { display: "flex", gap: 10, flexWrap: "wrap" },
    headerChip: {
        padding: "8px 12px",
        borderRadius: 999,
        background: "var(--surface-soft)",
        color: "var(--text-soft)",
        fontSize: 13,
        fontWeight: 700,
    },
    field: { display: "grid", gap: 8 },
    lookupRow: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) auto",
        gap: 8,
        alignItems: "center",
    },
    fieldLabel: { fontSize: 13, color: "var(--text-soft)", fontWeight: 700 },
    input: {
        width: "100%",
        padding: "12px 14px",
        borderRadius: 14,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
    },
    lookupInput: { cursor: "pointer" },
    tableCard: { padding: 14, display: "grid", gap: 14 },
    tableHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" },
    panelLabel: { color: "var(--text-soft)", textTransform: "uppercase", letterSpacing: "0.08em", fontSize: 11, fontWeight: 800 },
    billStatRow: { display: "flex", gap: 10, flexWrap: "wrap" },
    billStat: {
        padding: "8px 10px",
        borderRadius: 999,
        background: "var(--surface-soft)",
        fontSize: 12,
        fontWeight: 700,
    },
    itemCell: { display: "grid", gap: 4 },
    smallMuted: { color: "var(--text-soft)", fontSize: 12 },
    cellInput: {
        width: 92,
        padding: "9px 10px",
        borderRadius: 12,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
    },
    smallInput: {
        width: 64,
        padding: "8px 10px",
        borderRadius: 10,
        border: "1px solid var(--line)",
        background: "var(--surface)",
        color: "var(--text-main)",
    },
    removeIcon: {
        width: 34,
        height: 34,
        borderRadius: "50%",
        border: "1px solid var(--danger-soft-border)",
        background: "var(--danger-soft-bg)",
        color: "var(--status-error)",
        fontWeight: 800,
        cursor: "pointer",
    },
    emptyCell: { textAlign: "center", padding: "30px 14px", color: "var(--text-soft)" },
    warningText: { color: "var(--status-error)", fontWeight: 800 },
    warningBanner: {
        padding: "12px 14px",
        borderRadius: 16,
        background: "var(--warning-soft-bg)",
        color: "var(--warning-soft-text)",
        border: "1px solid var(--warning-soft-border)",
        fontWeight: 700,
    },
    captureFooterGrid: { display: "grid", gridTemplateColumns: "minmax(320px, 720px)", gap: 18 },
    paymentCard: { padding: 18, display: "grid", gap: 14 },
    paymentGrid: { display: "grid", gap: 12 },
    paymentRow: { display: "grid", gridTemplateColumns: "1fr 1fr 1.2fr auto", gap: 10 },
    singleSettleCard: {
        padding: 14,
        borderRadius: 16,
        background: "var(--surface-soft)",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        fontWeight: 800,
    },
    exchangeSummary: { display: "grid", gap: 10, padding: 14, borderRadius: 16, background: "var(--surface-soft)" },
    exchangeRow: { display: "flex", justifyContent: "space-between", gap: 12 },
    summaryCard: { padding: 18, display: "grid", gap: 10, alignContent: "start" },
    totalRow: { display: "flex", justifyContent: "space-between", gap: 12, color: "var(--text-soft)" },
    grandRow: {
        display: "flex",
        justifyContent: "space-between",
        gap: 12,
        paddingTop: 10,
        marginTop: 8,
        borderTop: "1px solid var(--line)",
        fontSize: 18,
        fontWeight: 800,
    },
    summaryActions: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 12 },
    payButton: {
        border: "none",
        borderRadius: 16,
        padding: "12px 16px",
        background: "var(--button-primary)",
        color: "#fff",
        fontWeight: 800,
        cursor: "pointer",
    },
    shortcutRail: {
        padding: 14,
        display: "grid",
        gap: 14,
        alignContent: "start",
        position: "sticky",
        top: 16,
    },
    shortcutRailHeader: { display: "grid", gap: 4 },
    shortcutList: { display: "grid", gap: 8 },
    shortcutButton: {
        display: "grid",
        gridTemplateColumns: "74px minmax(0, 1fr)",
        gap: 10,
        alignItems: "center",
        width: "100%",
        padding: "10px 12px",
        borderRadius: 16,
        border: "1px solid var(--line)",
        background: "#fff",
        textAlign: "left",
        cursor: "pointer",
    },
    shortcutKey: {
        color: "#b42318",
        fontWeight: 800,
        fontSize: 12,
        letterSpacing: "0.03em",
    },
    shortcutLabel: {
        color: "var(--text-main)",
        fontWeight: 700,
        fontSize: 14,
    },
    shortcutMeta: {
        display: "grid",
        gap: 6,
        padding: 12,
        borderRadius: 14,
        background: "var(--surface-soft)",
    },
    quickUtilityStack: { display: "grid", gap: 10 },
    scannerBody: { display: "grid", gap: 14 },
    scannerVideo: {
        width: "100%",
        minHeight: 320,
        borderRadius: 18,
        background: "#0f172a",
        objectFit: "cover",
    },
    scannerMount: {
        width: "100%",
        minHeight: 320,
        borderRadius: 18,
        overflow: "hidden",
        background: "#0f172a",
    },
    scannerHint: {
        padding: "12px 14px",
        borderRadius: 14,
        background: "var(--surface-soft)",
        color: "var(--text-soft)",
        fontWeight: 700,
    },
    scannerFallbackCard: {
        display: "grid",
        gap: 10,
        padding: 12,
        borderRadius: 14,
        background: "var(--surface-soft)",
    },
    sideList: { display: "grid", gap: 10, maxHeight: 420, overflowY: "auto" },
    recentBill: {
        display: "grid",
        gap: 4,
        textAlign: "left",
        border: "1px solid var(--line)",
        borderRadius: 16,
        padding: 14,
        background: "#fff",
        cursor: "pointer",
    },
    modalBackdrop: {
        position: "fixed",
        inset: 0,
        background: "var(--modal-backdrop-bg)",
        display: "grid",
        placeItems: "center",
        padding: 24,
        zIndex: 50,
    },
    modalCard: {
        width: "min(100%, 1100px)",
        maxHeight: "88vh",
        overflowY: "auto",
        padding: 20,
        display: "grid",
        gap: 16,
        background: "var(--surface)",
        border: "1px solid var(--line)",
        borderRadius: 24,
    },
    modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
    billingActionTopRow: {
        display: "grid",
        gridTemplateColumns: "0.7fr 2fr 1fr 2fr",
        gap: 10,
    },
    billingActionInput: {
        width: "100%",
        padding: "11px 12px",
        border: "1px solid var(--line)",
        borderRadius: 0,
        background: "#fff",
        fontSize: 14,
    },
    billingActionInputWide: {
        width: "100%",
        padding: "11px 12px",
        border: "1px solid var(--line)",
        borderRadius: 0,
        background: "#fff",
        fontSize: 14,
    },
    billingActionCustomerPanel: {
        border: "1px solid var(--line)",
        background: "#d4d4d4",
        minHeight: 150,
    },
    billingActionCustomerHeader: {
        display: "grid",
        gridTemplateColumns: "1fr 2fr 1fr 2fr",
        background: "#fff",
        borderBottom: "1px solid var(--line)",
        fontSize: 13,
        fontWeight: 600,
    },
    billingActionCustomerBody: {
        minHeight: 128,
    },
    billingActionSummaryBar: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "12px 14px",
        border: "1px solid var(--line)",
        background: "var(--surface-soft)",
        fontWeight: 700,
    },
    billingActionFooter: {
        display: "flex",
        gap: 10,
        alignItems: "center",
        flexWrap: "wrap",
    },
    billingActionFooterEnd: {
        display: "flex",
        gap: 10,
        justifyContent: "flex-end",
        alignItems: "center",
        flexWrap: "wrap",
    },
    cardUpiTable: {
        border: "1px solid var(--line)",
        background: "#fff",
    },
    cardUpiTableHeader: {
        display: "grid",
        gridTemplateColumns: "0.4fr 2.5fr 1fr 1fr 1fr 1fr 1fr",
        gap: 0,
        background: "var(--surface-soft)",
        borderBottom: "1px solid var(--line)",
        fontWeight: 700,
        fontSize: 13,
    },
    cardUpiTableRow: {
        display: "grid",
        gridTemplateColumns: "0.4fr 2.5fr 1fr 1fr 1fr 1fr 1fr",
        gap: 0,
        alignItems: "center",
        fontSize: 14,
        borderBottom: "1px solid var(--line)",
    },
    cardUpiTableTotalRow: {
        display: "grid",
        gridTemplateColumns: "0.4fr 2.5fr 1fr 1fr 1fr 1fr 1fr",
        gap: 0,
        alignItems: "center",
        fontSize: 14,
        background: "#f5f5f5",
    },
    cardUpiEnterCell: {
        border: "none",
        background: "transparent",
        color: "var(--accent)",
        fontWeight: 800,
        cursor: "pointer",
        padding: "12px 10px",
        textAlign: "left",
    },
    paymentOptionTableInput: {
        width: "100%",
        minWidth: 0,
        border: "none",
        borderLeft: "1px solid var(--line)",
        padding: "12px 14px",
        background: "var(--surface)",
        color: "var(--text-main)",
        outline: "none",
    },
    iconButton: {
        width: 36,
        height: 36,
        borderRadius: "50%",
        border: "1px solid var(--line)",
        background: "#fff",
        cursor: "pointer",
        fontWeight: 800,
    },
    modalColumns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 },
    customerModalBody: { display: "grid", gap: 16 },
    customerSearchCard: {
        display: "grid",
        gap: 12,
        padding: 16,
        borderRadius: 18,
        background: "var(--surface-soft)",
    },
    customerSearchHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        flexWrap: "wrap",
    },
    customerActionRow: { display: "flex", gap: 10, flexWrap: "wrap" },
    customerSearchInput: {
        width: "100%",
        padding: "13px 14px",
        borderRadius: 14,
        border: "1px solid var(--line)",
        background: "#fff",
        fontSize: 15,
    },
    customerTableWrap: {
        borderRadius: 18,
        border: "1px solid var(--line)",
        background: "#fff",
        overflow: "hidden",
    },
    customerTableActions: {
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
    },
    customerFormCard: {
        padding: 18,
        display: "grid",
        gap: 16,
    },
    customerFormHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        flexWrap: "wrap",
    },
    customerFormGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: 14,
    },
    customerLegacyForm: {
        display: "grid",
        gap: 14,
        padding: 14,
        borderRadius: 16,
        background: "linear-gradient(135deg, #f7faf4 0%, #edf1ea 100%)",
        border: "1px solid var(--line)",
        boxShadow: "inset 0 0 0 1px var(--app-surface-tint-strong)",
    },
    legacyTopRow: {
        display: "grid",
        gridTemplateColumns: "1fr 0.9fr 1.5fr",
        gap: 12,
    },
    legacyDateRow: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 24,
    },
    legacyField: {
        display: "grid",
        gridTemplateColumns: "86px minmax(0, 1fr)",
        alignItems: "center",
        gap: 8,
    },
    legacyFieldWide: {
        display: "grid",
        gridTemplateColumns: "122px minmax(0, 1fr)",
        alignItems: "center",
        gap: 8,
    },
    legacyRowField: {
        display: "grid",
        gridTemplateColumns: "86px minmax(0, 1fr)",
        alignItems: "center",
        gap: 8,
    },
    legacyLabel: {
        color: "var(--text-soft)",
        fontWeight: 700,
        textAlign: "right",
        whiteSpace: "nowrap",
    },
    legacyInput: {
        width: "100%",
        minHeight: 32,
        padding: "6px 10px",
        borderRadius: 10,
        border: "1px solid var(--line)",
        background: "#fff",
        fontSize: 15,
    },
    legacyReadonlyInput: {
        background: "var(--surface-soft)",
        color: "var(--text-soft)",
        fontWeight: 700,
    },
    b2bSection: {
        display: "grid",
        gap: 12,
        padding: "14px 10px 10px",
        border: "1px solid var(--line)",
        position: "relative",
        background: "var(--app-surface-tint)",
        borderRadius: 14,
    },
    b2bLegend: {
        position: "absolute",
        top: -11,
        left: 10,
        padding: "0 6px",
        background: "#f7faf4",
        color: "var(--text-main)",
        fontWeight: 800,
        fontSize: 14,
    },
    b2bGstinRow: {
        display: "grid",
        gridTemplateColumns: "1fr auto",
        gap: 14,
        alignItems: "center",
    },
    customerLegacyActions: {
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
        paddingTop: 4,
    },
    filterGrid: { display: "grid", gridTemplateColumns: "repeat(5, minmax(0, 1fr))", gap: 12 },
    selectedTableRow: {
        background: "rgba(22, 120, 84, 0.12)",
        outline: "2px solid rgba(22, 120, 84, 0.3)",
        outlineOffset: "-2px",
    },
    selectedCard: {
        borderColor: "var(--accent)",
        boxShadow: "0 0 0 2px rgba(22, 120, 84, 0.18)",
        background: "rgba(22, 120, 84, 0.08)",
    },
    exchangeList: { display: "grid", gap: 16 },
    exchangeSaleCard: { border: "1px solid var(--line)", borderRadius: 18, padding: 14, display: "grid", gap: 12 },
    exchangeSaleHeader: { display: "flex", gap: 14, flexWrap: "wrap", alignItems: "center" },
    inlineQtyControl: { display: "flex", gap: 8, alignItems: "center" },
    heldBillCard: {
        display: "flex",
        justifyContent: "space-between",
        gap: 12,
        alignItems: "center",
        padding: 14,
        borderRadius: 16,
        border: "1px solid var(--line)",
        background: "#fff",
    },
    discountInfo: {
        padding: "12px 14px",
        borderRadius: 16,
        background: "var(--surface-soft)",
        color: "var(--text-soft)",
        fontWeight: 700,
    },
    summaryPreview: { display: "grid", gap: 10, borderRadius: 18, background: "var(--surface-soft)", padding: 14 },
    summaryLine: { display: "flex", justifyContent: "space-between", gap: 12 },
};


export default styles;
