import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Utility to export report data to PDF
export const exportReportToPDF = (data, reportType, appSettings = {}) => {
    const doc = new jsPDF();

    // Company branding
    const companyName = appSettings.companyName || 'POS System';
    const counterName = appSettings.billingCounter || 'Main Counter';

    // Header
    doc.setFontSize(20);
    doc.text(companyName, 20, 20);
    doc.setFontSize(12);
    doc.text(counterName, 20, 30);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 40);

    let yPosition = 50;

    // Report title
    doc.setFontSize(16);
    doc.text(`${reportType} Report`, 20, yPosition);
    yPosition += 20;

    // Handle different report types
    switch (reportType) {
        case 'Sales':
            yPosition = addSalesReportTable(doc, data, yPosition);
            break;
        case 'Purchase':
            yPosition = addPurchaseReportTable(doc, data, yPosition);
            break;
        case 'Stock':
            yPosition = addStockReportTable(doc, data, yPosition);
            break;
        case 'GST':
            yPosition = addGSTReportTable(doc, data, yPosition);
            break;
        case 'Profit & Loss':
            yPosition = addProfitLossTable(doc, data, yPosition);
            break;
        case 'Cash Book':
            yPosition = addCashBookTable(doc, data, yPosition);
            break;
        default:
            doc.text('Report data not available', 20, yPosition);
    }

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.text('Generated by POS System', 20, pageHeight - 20);

    // Save the PDF
    doc.save(`${reportType.toLowerCase()}-report-${new Date().toISOString().split('T')[0]}.pdf`);
};

// Helper functions for each report type
const addSalesReportTable = (doc, data, yPosition) => {
    if (!data.sales || data.sales.length === 0) {
        doc.text('No sales data available', 20, yPosition);
        return yPosition + 20;
    }

    const tableData = data.sales.map(sale => [
        sale.billNo || '-',
        sale.customer || 'Walk-in',
        sale.customerPhone || '-',
        new Date(sale.saleDate).toLocaleDateString(),
        `Rs. ${sale.totalAmount?.toFixed(2) || '0.00'}`
    ]);

    doc.autoTable({
        head: [['Bill No', 'Customer', 'Phone', 'Date', 'Total Amount']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [41, 128, 185] }
    });

    return doc.lastAutoTable.finalY + 20;
};

const addPurchaseReportTable = (doc, data, yPosition) => {
    if (!data.purchases || data.purchases.length === 0) {
        doc.text('No purchase data available', 20, yPosition);
        return yPosition + 20;
    }

    const tableData = data.purchases.map(purchase => [
        purchase.billNo || '-',
        purchase.supplier || '-',
        new Date(purchase.purchaseDate).toLocaleDateString(),
        `Rs. ${purchase.totalAmount?.toFixed(2) || '0.00'}`
    ]);

    doc.autoTable({
        head: [['Bill No', 'Supplier', 'Date', 'Total Amount']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [52, 152, 219] }
    });

    return doc.lastAutoTable.finalY + 20;
};

const addStockReportTable = (doc, data, yPosition) => {
    if (!data.inventory || data.inventory.length === 0) {
        doc.text('No stock data available', 20, yPosition);
        return yPosition + 20;
    }

    const tableData = data.inventory.map(item => [
        item.name || '-',
        item.category?.name || '-',
        item.brand?.name || '-',
        item.stock || 0,
        `Rs. ${item.sellingRate?.toFixed(2) || '0.00'}`,
        `Rs. ${(item.stock * item.sellingRate)?.toFixed(2) || '0.00'}`
    ]);

    doc.autoTable({
        head: [['Item Name', 'Category', 'Brand', 'Stock', 'Rate', 'Value']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [155, 89, 182] }
    });

    return doc.lastAutoTable.finalY + 20;
};

const addGSTReportTable = (doc, data, yPosition) => {
    if (!data.gstData) {
        doc.text('No GST data available', 20, yPosition);
        return yPosition + 20;
    }

    const gstData = data.gstData;
    const tableData = [
        ['Input GST', `Rs. ${gstData.inputGST?.toFixed(2) || '0.00'}`],
        ['Output GST', `Rs. ${gstData.outputGST?.toFixed(2) || '0.00'}`],
        ['GST Payable', `Rs. ${gstData.payableGST?.toFixed(2) || '0.00'}`]
    ];

    doc.autoTable({
        head: [['GST Type', 'Amount']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [230, 126, 34] }
    });

    return doc.lastAutoTable.finalY + 20;
};

const addProfitLossTable = (doc, data, yPosition) => {
    if (!data.profitLoss) {
        doc.text('No profit & loss data available', 20, yPosition);
        return yPosition + 20;
    }

    const plData = data.profitLoss;
    const tableData = [
        ['Net Sales', `Rs. ${plData.netSales?.toFixed(2) || '0.00'}`],
        ['Net Purchases', `Rs. ${plData.netPurchases?.toFixed(2) || '0.00'}`],
        ['Gross Profit', `Rs. ${plData.grossProfit?.toFixed(2) || '0.00'}`]
    ];

    doc.autoTable({
        head: [['Item', 'Amount']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [46, 204, 113] }
    });

    return doc.lastAutoTable.finalY + 20;
};

const addCashBookTable = (doc, data, yPosition) => {
    if (!data.cashBook || data.cashBook.length === 0) {
        doc.text('No cash book data available', 20, yPosition);
        return yPosition + 20;
    }

    const tableData = data.cashBook.map(entry => [
        new Date(entry.date).toLocaleDateString(),
        entry.description || '-',
        entry.type || '-',
        `Rs. ${entry.amount?.toFixed(2) || '0.00'}`
    ]);

    doc.autoTable({
        head: [['Date', 'Description', 'Type', 'Amount']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [149, 165, 166] }
    });

    return doc.lastAutoTable.finalY + 20;
};